version: "3.8"

services:
  validator:
    build: .
    container_name: validator
    env_file:
      .env
    volumes:
      - ./csv:/app/csv

  redis:
    image: redis:alpine3.15
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data